### ISSUE TITLE
PAL Gamecube Intro Slowdowns + Swiss do not start

### ISSUE THREAD

**Issue by Fgo988** [OffBroadway/cubeboot#5]
Hallo,

do not get it to work properly with my Pal Gamecube with Qoob Pro (iplboot installed).
Either I get a Blackscreen directly after the Startup of the Gamecube or the Intro will start with extrem slowdowns (sound seems to be in the normal speed) and than I will get a Blacksreen.
I think it is an issue of Pal systems, in the Readme it is written that pal systems are supported.

**Comment by samzanemesis** [comment]
This happened to me while using GCVideo only, on composite it seems normal

**Comment by samzanemesis** [comment]
Disabling 480p mode makes it go normal

I've noticed the picture gets really distorted as well when on the slowdown

**Comment by samzanemesis** [comment]
Sometimes it seems there's uninitialised memory that makes it trigger the start_game bool on the first frame of boot, that makes me able to boot to Swiss correctly on 480p

Could there be an option to just force that directly eg holding reset button on boot to skip the boot animation entirely?

**Comment by Fgo988** [comment]
> This happened to me while using GCVideo only, on composite it seems normal

You are right, I use the GCVideo.
Now i used the Original Composite Cable on an old CRT and it worked.
I already tried to change the settings on the GCVideo, but no setting seems to be the solution.
Maybe this will be fixed in an later Version. The old CRT is no Option any more.

**Comment by trevor403** [comment]
I have just ordered a PAL DOL-001 GameCube and it should get here in a week or two. I will start working on this issue soon! Thanks got the details folks

**Comment by trevor403** [comment]
We also need to detect any IPL revision 1.0 and disable the Progressive patch

**Comment by samzanemesis** [comment]
You're a champ, thanks

**Comment by trevor403** [comment]
Fix is in https://github.com/OffBroadway/flippyboot-ipl/tree/gcloader-update

I will bake it into the next release.

**Comment by trevor403** [comment]
Resolved by [Release v0.1.2](https://github.com/OffBroadway/flippyboot-ipl/releases/tag/v0.1.2)

If you have any issues please comment bellow

**Comment by Fgo988** [comment]
> Resolved by [Release v0.1.2](https://github.com/OffBroadway/flippyboot-ipl/releases/tag/v0.1.2)
> 
> If you have any issues please comment bellow

Thanks for the Update. 
With the Update the Boot animation seems to have the normal speed and swiss start after the animation.

At first I thougth it still does not work. But than I realised the loading times are now extremly long.

I checked/compared them with a stopwatch.
v0.1.0 with the Composite Cable:
~3 seconds till the Animation starts
~4 seconds till swiss starts, after the animation stops

v0.1.3 with GCVideo/GCplug:
~14 seconds till the Animation starts
~13 seconds till swiss starts, after the animation stops

**Comment by samzanemesis** [comment]
Just flashed .13

Works perfectly here, thank you again, let me know if there's any way I can support your work

**Comment by trevor403** [comment]
It seems that people are not able to use GCVideo in Progressive mode with PAL IPL v1.0. I am still investigating how we can make this possible.

**Comment by Fgo988** [comment]
Today I could check it again and I tried different settings.

I have 2 Gamecubes, both Pal with IPL v1.0. One with a Qoob Pro the second one with a Picoboot. On both consoles Cubeboot is installed with the SD mounting setup, to use the different SD Cards in both consoles.

With Cubeboot 0.1.0 the animation is too slow with the GCVideo adapter, with the Composite cable it looks normal.
With Cubeboot 0.1.3 the animation works normally, but the loading times are slow. This can be seen with the GCVideo Adpter and the composite cable!
So for me, one console works acutally with Cubeboot 0.1.0 and the Composite cable.
On the other console with GCVideo I deleted Cubeboot, 0.1.0 does not work and with 0.1.3 I always think the console is broken, because it took so long to load.

Maybe this helps to find a solution.

**Comment by trevor403** [comment]
I was finally able to get progressive scan working on PAL unites by using an NTSC 480p 60fps video mode https://github.com/OffBroadway/flippyboot-ipl/commit/a872b6b03c32909188ef8db29d0f50db8c632ad5

**Comment by ianflett** [comment]
I installed my PicoBoot today and initially thought I'd botched the install. Long story short, with a new card and just Swiss everything working as expected, but with Flippyboot it shows the loader then transitions to a black screen and never initiates Swiss. As you may have guessed, I have a PAL console, but I don't know what IPL version - I'd guess at 1.0?

Otherwise, Flippyboot looks great and I would love to use it. If there's any further information I can provided to help, please ask.
